#include <stdio.h>
#include <stdlib.h>
#include <math.h> // math for exponential function
#include <time.h> // time for seeding
#include <pthread.h> // include pthread functions and structures
#include <semaphore.h> // include semaphores
#include <unistd.h> // include sleep
#include <string.h>
#include <fcntl.h>
#include <sys/shm.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <stdbool.h>

char* BUFFER_NAME; //Name of the shared buffer
int MEDIUM_SECONDS; //Medium duration for the message creation

const char * NAME_MEMORY_TOTALPRODUCERS = "SHARED_MEMORY_TOTALPRODUCERS";
int SHAREDM_FILEDESCRIPTOR_TOTALPRODUCERS;   //shared memory file discriptor the total of producers created
int * TOTAL_PRODUCERS; //Total of producers created

const char * NAME_MEMORY_SUSPEND = "SHARED_MEMORY_SUSPEND";
int SHAREDM_FILEDESCRIPTOR_SUSPEND;   //shared memory file discriptor for suspend process
bool * SUSPEND; //If true suspend the process

int MESSAGE_COUNTER; //Count the total of messages generated by the producer
double TOTAL_TIME_WAITING; //Count the total time waiting to generate a message
double TOTAL_TIME_BLOCKED; //Count the total time blocked by semaphores

const char * name = "shared_memory";
const char * sema1= "fill";
const char * sema2= "avail";
const char * sema3= "mutex";
int shm_fd;   //shared memory file discriptor
int * shelf;
int loop=6;  
sem_t * fill, * avail, * mutex;

int getRandomNumber(){
  int lower = 0, upper = 4; 
  // Use current time as  
  // seed for random generator 
  srand(time(0)); 
  int num = (rand() % (upper - lower + 1)) + lower; 
  printf("Random number: %d \n", num);
}

//Random number for not declared directiion.
double ran_expo(double lambda){
    double u;
    u = rand() / (RAND_MAX + 1.0);
    return -log(1- u) / lambda;
}

int main(int argc, char *argv[]) {
   // variables to store date and time components
	int hours, minutes, seconds, day, month, year;

	// time_t is arithmetic time type
	time_t now;
	
	// Obtain current time
	// time() returns the current time of the system as a time_t value
	time(&now);

  // localtime converts a time_t value to calendar time and 
	// returns a pointer to a tm structure with its members 
	// filled with the corresponding values
	struct tm *local = localtime(&now);

  hours = local->tm_hour;      	// get hours since midnight (0-23)
  minutes = local->tm_min;     	// get minutes passed after the hour (0-59)
  seconds = local->tm_sec;     	// get seconds passed after minute (0-59)

  day = local->tm_mday;        	// get day of month (1 to 31)
  month = local->tm_mon + 1;   	// get month of year (0 to 11)
  year = local->tm_year + 1900;	// get year since 1900

  printf("Process id: %i\n", getpid());
	// print local time
	if (hours < 12)	// before midday
		printf("%02d/%02d/%d %02d:%02d:%02d am\n", day, month, year, hours, minutes, seconds);

	else	// after midday
		printf("%02d/%02d/%d %02d:%02d:%02d pm\n", day, month, year, hours - 12, minutes, seconds);

    
   if (argc <= 2) {
      printf("Specify buffer name and medium in seconds\n");
      exit(0);
  } else {
      BUFFER_NAME = argv[1];
      MEDIUM_SECONDS  = atoi(argv[2]);
  }
   printf("Buffer name: %s\n", BUFFER_NAME);

  /* make * shelf shared between processes*/
    //create the shared memory segment
    shm_fd = shm_open(name, O_CREAT | O_RDWR, 0666);
    //configure the size of the shared memory segment
    ftruncate(shm_fd,sizeof(int));
    //map the shared memory segment in process address space
    shelf = mmap(0,sizeof(int), PROT_READ | PROT_WRITE, MAP_SHARED, shm_fd, 0);
    /* creat/open semaphores*/
    //cook post semaphore fill after cooking a pizza
    fill = sem_open(sema1, O_CREAT,0666,0);
    //waiter post semaphore avail after picking up a pizza, at the beginning avail=3
    avail = sem_open(sema2, O_CREAT, 0666, 3);
    //mutex for mutual exclusion of shelf
    mutex = sem_open(sema3,O_CREAT,0666,1);

    printf("\nProducer making messages.\n");
    time_t begin = time(NULL);

     while(loop--){
       sleep(1);
        /*sem_wait(avail);
        sleep(rand()%2+1);
        sem_wait(mutex);
        (* shelf)++;
        sem_post(mutex);
        printf("Cook: cook a pizza, there are %d pizza now\n", * shelf);
        sem_post(fill);*/
    }
    

    /* here, do your time-consuming job */

    time_t end = time(NULL);

    // calculate elapsed time by finding difference (end - begin)
    printf("Time elpased is %d seconds\n", (end - begin));

      /* close and unlink semaphores*/
    sem_close(fill);
    sem_close(avail);
    sem_close(mutex);
    sem_unlink(sema1);
    sem_unlink(sema2);
    sem_unlink(sema3);
      /* close and unlink shared memory*/
      munmap(shelf, sizeof(int));
    close(shm_fd);
    shm_unlink(name);
  sleep(1);
  exit(0);
}
